<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DT-TECH-2D80" name="testCases.DatabaseCheckChecker" tests="165" failures="0" timestamp="07 Mar 2018 10:22:30 GMT" time="170.866" errors="6">
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.051" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.045" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.018" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.000" classname="testCases.DatabaseCheckChecker">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseChecker(AppKeywords.java:630)at testKeywords.Keyword.executeKeywords(Keyword.java:252)at testCases.DatabaseCheckChecker.loginTest(DatabaseCheckChecker.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.158" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.040" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.000" classname="testCases.DatabaseCheckChecker">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseChecker(AppKeywords.java:630)at testKeywords.Keyword.executeKeywords(Keyword.java:252)at testCases.DatabaseCheckChecker.loginTest(DatabaseCheckChecker.java:39)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.035" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.018" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.158" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.041" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.044" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.158" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.016" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.038" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.079" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.000" classname="testCases.DatabaseCheckChecker">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseChecker(AppKeywords.java:630)at testKeywords.Keyword.executeKeywords(Keyword.java:252)at testCases.DatabaseCheckChecker.loginTest(DatabaseCheckChecker.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.267" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.000" classname="testCases.DatabaseCheckChecker">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseChecker(AppKeywords.java:630)at testKeywords.Keyword.executeKeywords(Keyword.java:252)at testCases.DatabaseCheckChecker.loginTest(DatabaseCheckChecker.java:39)at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.064" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.000" classname="testCases.DatabaseCheckChecker">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseChecker(AppKeywords.java:630)at testKeywords.Keyword.executeKeywords(Keyword.java:252)at testCases.DatabaseCheckChecker.loginTest(DatabaseCheckChecker.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.000" classname="testCases.DatabaseCheckChecker">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1at testKeywords.AppKeywords.SelectDatabaseChecker(AppKeywords.java:630)at testKeywords.Keyword.executeKeywords(Keyword.java:252)at testCases.DatabaseCheckChecker.loginTest(DatabaseCheckChecker.java:39)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.064" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.049" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.032" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.048" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.017" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.018" classname="testCases.DatabaseCheckChecker"/>
  <testcase name="loginTest" time="1.033" classname="testCases.DatabaseCheckChecker"/>
</testsuite> <!-- testCases.DatabaseCheckChecker -->
